"""Add policy_requests table

Revision ID: f5984b0420a8
Revises: 16f7afca8821
Create Date: 2026-07-30 13:18:47.625538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5984b0420a8'
down_revision = '16f7afca8821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('policy_type', sa.String(length=50), nullable=True),
    sa.Column('desired_coverage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_requests')
    # ### end Alembic commands ###
